const brightNGC = [
  {
    id: "NGC 869",
    name: "h Persei (Double Cluster)",
    type: "Open Cluster",
    mag: 4.3,
    size: "30 arcmin",
    ra: 2.3333,
    dec: 57.15,
    image: "images/full/ngc869.jpg",
    desc: "One half of the famous Double Cluster in Perseus, rich with young stars."
  },
  {
    id: "NGC 884",
    name: "χ Persei (Double Cluster)",
    type: "Open Cluster",
    mag: 4.4,
    size: "30 arcmin",
    ra: 2.3833,
    dec: 57.15,
    image: "images/full/ngc884.jpg",
    desc: "The second half of the Double Cluster, neighboring NGC 869."
  },
  {
    id: "NGC 253",
    name: "Sculptor Galaxy",
    type: "Spiral Galaxy",
    mag: 7.1,
    size: "27x7 arcmin",
    ra: 0.7917,
    dec: -25.2833,
    image: "images/full/ngc253.jpg",
    desc: "A bright spiral galaxy in Sculptor, also called the Silver Coin Galaxy."
  },
  {
    id: "NGC 300",
    name: "Spiral Galaxy",
    type: "Spiral Galaxy",
    mag: 8.1,
    size: "22x15 arcmin",
    ra: 0.9167,
    dec: -37.6833,
    image: "images/full/ngc300.jpg",
    desc: "A nearby spiral galaxy in Sculptor, part of the Sculptor Group."
  },
  {
    id: "NGC 404",
    name: "Mirach's Ghost",
    type: "Lenticular Galaxy",
    mag: 11.2,
    size: "3.5 arcmin",
    ra: 1.1,
    dec: 35.7167,
    image: "images/full/ngc404.jpg",
    desc: "A small galaxy close to the bright star Mirach in Andromeda."
  },
  {
    id: "NGC 457",
    name: "Owl Cluster",
    type: "Open Cluster",
    mag: 6.4,
    size: "20 arcmin",
    ra: 1.3167,
    dec: 58.3,
    image: "images/full/ngc457.jpg",
    desc: "A famous open cluster in Cassiopeia, nicknamed for its owl-like shape."
  },
  {
    id: "NGC 7000",
    name: "North America Nebula",
    type: "Emission Nebula",
    mag: 4.0,
    size: "120 arcmin",
    ra: 20.95,
    dec: 44.3333,
    image: "images/full/ngc7000.jpg",
    desc: "A large nebula in Cygnus, shaped like the continent of North America."
  },
  {
    id: "NGC 281",
    name: "Pacman Nebula",
    type: "Emission Nebula",
    mag: 7.4,
    size: "35 arcmin",
    ra: 0.8833,
    dec: 56.6333,
    image: "images/full/ngc281.jpg",
    desc: "A bright nebula in Cassiopeia with star-forming regions."
  },
  {
    id: "NGC 891",
    name: "Edge-on Spiral Galaxy",
    type: "Spiral Galaxy",
    mag: 9.9,
    size: "14x3 arcmin",
    ra: 2.3833,
    dec: 42.3333,
    image: "images/full/ngc891.jpg",
    desc: "A beautiful edge-on spiral galaxy in Andromeda, similar to the Milky Way."
  },
  {
    id: "NGC 1499",
    name: "California Nebula",
    type: "Emission Nebula",
    mag: 6.0,
    size: "145 arcmin",
    ra: 4.0,
    dec: 36.5833,
    image: "images/full/ngc1499.jpg",
    desc: "A large emission nebula in Perseus, shaped like California."
  },
  {
    id: "NGC 2024",
    name: "Flame Nebula",
    type: "Emission Nebula",
    mag: 8.0,
    size: "30 arcmin",
    ra: 5.95,
    dec: -1.9833,
    image: "images/full/ngc2024.jpg",
    desc: "A bright nebula near Alnitak in Orion’s Belt."
  },
  {
    id: "NGC 2022",
    name: "Planetary Nebula",
    type: "Planetary Nebula",
    mag: 11.7,
    size: "0.4 arcmin",
    ra: 5.9333,
    dec: 9.05,
    image: "images/full/ngc2022.jpg",
    desc: "A faint planetary nebula in Orion."
  },
  {
    id: "NGC 2023",
    name: "Reflection Nebula",
    type: "Reflection Nebula",
    mag: 10.0,
    size: "10 arcmin",
    ra: 5.95,
    dec: -2.0667,
    image: "images/full/ngc2023.jpg",
    desc: "A bright reflection nebula near the Horsehead region."
  },
  {
    id: "NGC 2025",
    name: "Nebula near Flame",
    type: "Emission Nebula",
    mag: 11.0,
    size: "15 arcmin",
    ra: 5.9667,
    dec: -1.9667,
    image: "images/full/ngc2025.jpg",
    desc: "Part of the nebulous complex near the Flame Nebula in Orion."
  },
  {
    id: "NGC 2244",
    name: "Cluster in Rosette Nebula",
    type: "Open Cluster",
    mag: 4.8,
    size: "24 arcmin",
    ra: 6.5,
    dec: 5.0,
    image: "images/full/ngc2244.jpg",
    desc: "The bright open cluster that illuminates the Rosette Nebula."
  },
  {
    id: "NGC 2261",
    name: "Hubble's Variable Nebula",
    type: "Reflection Nebula",
    mag: 9.0,
    size: "2x1 arcmin",
    ra: 6.0833,
    dec: 8.4833,
    image: "images/full/ngc2261.jpg",
    desc: "A variable reflection nebula in Monoceros, discovered by William Herschel."
  },
  {
    id: "NGC 2392",
    name: "Eskimo Nebula",
    type: "Planetary Nebula",
    mag: 9.2,
    size: "0.8 arcmin",
    ra: 7.4,
    dec: 20.9167,
    image: "images/full/ngc2392.jpg",
    desc: "A bright planetary nebula in Gemini, nicknamed the Clown Face Nebula."
  },
  {
    id: "NGC 2403",
    name: "Spiral Galaxy",
    type: "Spiral Galaxy",
    mag: 8.9,
    size: "22x12 arcmin",
    ra: 7.6333,
    dec: 65.6,
    image: "images/full/ngc2403.jpg",
    desc: "A bright spiral galaxy in Camelopardalis, part of the M81 Group."
  },
  {
    id: "NGC 2683",
    name: "UFO Galaxy",
    type: "Spiral Galaxy",
    mag: 9.7,
    size: "9x3 arcmin",
    ra: 8.75,
    dec: 33.4167,
    image: "images/full/ngc2683.jpg",
    desc: "An edge-on spiral galaxy in Lynx, nicknamed the UFO Galaxy."
  },
  {
    id: "NGC 2903",
    name: "Spiral Galaxy",
    type: "Spiral Galaxy",
    mag: 8.9,
    size: "12.6x6 arcmin",
    ra: 9.55,
    dec: 21.4167,
    image: "images/full/ngc2903.jpg",
    desc: "A bright barred spiral galaxy in Leo, often overlooked near Regulus."
  },
  {
    id: "NGC 3115",
    name: "Spindle Galaxy",
    type: "Lenticular Galaxy",
    mag: 9.2,
    size: "7.2x2.5 arcmin",
    ra: 10.05,
    dec: -7.7167,
    image: "images/full/ngc3115.jpg",
    desc: "A bright edge-on lenticular galaxy in Sextans."
  },
  {
    id: "NGC 3242",
    name: "Ghost of Jupiter",
    type: "Planetary Nebula",
    mag: 8.6,
    size: "0.5 arcmin",
    ra: 10.25,
    dec: -18.65,
    image: "images/full/ngc3242.jpg",
    desc: "A planetary nebula in Hydra resembling Jupiter’s disk."
  },
  {
    id: "NGC 3628",
    name: "Hamburger Galaxy",
    type: "Spiral Galaxy",
    mag: 9.5,
    size: "15x4 arcmin",
    ra: 11.25,
    dec: 13.35,
    image: "images/full/ngc3628.jpg",
    desc: "An edge-on spiral galaxy in Leo, part of the Leo Triplet."
  },
  {
    id: "NGC 4027",
    name: "Ringtail Galaxy",
    type: "Spiral Galaxy",
    mag: 11.7,
    size: "3.2x2.4 arcmin",
    ra: 11.9833,
    dec: -19.0,
    image: "images/full/ngc4027.jpg",
    desc: "A peculiar spiral galaxy in Corvus with a distorted arm."
  },
  {
    id: "NGC 4038",
    name: "Antennae Galaxies",
    type: "Interacting Galaxies",
    mag: 10.3,
    size: "5 arcmin",
    ra: 12.0,
    dec: -18.9,
    image: "images/full/ngc4038.jpg",
    desc: "One of the famous Antennae Galaxies in Corvus, colliding with NGC 4039."
  },
  {
    id: "NGC 4039",
    name: "Antennae Galaxies",
    type: "Interacting Galaxies",
    mag: 10.3,
    size: "5 arcmin",
    ra: 12.0,
    dec: -18.9,
    image: "images/full/ngc4039.jpg",
    desc: "The second Antennae Galaxy in Corvus, interacting with NGC 4038."
  },
  {
    id: "NGC 4151",
    name: "Eye of Sauron Galaxy",
    type: "Spiral Galaxy",
    mag: 10.5,
    size: "6x3 arcmin",
    ra: 12.1667,
    dec: 39.7167,
    image: "images/full/ngc4151.jpg",
    desc: "A Seyfert galaxy in Canes Venatici, nicknamed for its bright nucleus."
  },
  {
    id: "NGC 4565",
    name: "Needle Galaxy",
    type: "Edge-on Spiral Galaxy",
    mag: 9.6,
    size: "15.9x1.9 arcmin",
    ra: 12.6167,
    dec: 25.9833,
    image: "images/full/ngc4565.jpg",
    desc: "A stunning edge-on spiral galaxy in Coma Berenices."
  },
  {
    id: "NGC 4631",
    name: "Whale Galaxy",
    type: "Spiral Galaxy",
    mag: 9.3,
    size: "15x3 arcmin",
    ra: 12.6167,
    dec: 32.1333,
    image: "images/full/ngc4631.jpg",
    desc: "A large spiral galaxy in Canes Venatici, resembling a whale."
  },
  {
    id: "NGC 4656",
    name: "Hockey Stick Galaxy",
    type: "Spiral Galaxy",
    mag: 10.4,
    size: "15x3 arcmin",
    ra: 12.7,
    dec: 32.5,
    image: "images/full/ngc4656.jpg",
    desc: "A distorted spiral galaxy in Canes Venatici, near NGC 4631."
  },
  {
    id: "NGC 4697",
    name: "Elliptical Galaxy",
    type: "Elliptical Galaxy",
    mag: 9.2,
    size: "7.4 arcmin",
    ra: 12.8,
    dec: -5.8,
    image: "images/full/ngc4697.jpg",
    desc: "A bright elliptical galaxy in Virgo."
  },
  {
    id: "NGC 4755",
    name: "Jewel Box Cluster",
    type: "Open Cluster",
    mag: 4.2,
    size: "10 arcmin",
    ra: 12.7833,
    dec: -60.35,
    image: "images/full/ngc4755.jpg",
    desc: "A colorful open cluster in Crux, visible to the naked eye in the southern sky."
  },
  {
    id: "NGC 5128",
    name: "Centaurus A",
    type: "Radio Galaxy",
    mag: 6.8,
    size: "25x20 arcmin",
    ra: 13.4167,
    dec: -43.0167,
    image: "images/full/ngc5128.jpg",
    desc: "A peculiar radio galaxy in Centaurus with a dark dust lane."
  },
  {
    id: "NGC 5139",
    name: "Omega Centauri",
    type: "Globular Cluster",
    mag: 3.7,
    size: "36 arcmin",
    ra: 13.45,
    dec: -47.4667,
    image: "images/full/ngc5139.jpg",
    desc: "The largest and brightest globular cluster in the sky, naked-eye visible."
  },
  {
    id: "NGC 5194",
    name: "Whirlpool Galaxy",
    type: "Spiral Galaxy",
    mag: 8.4,
    size: "11x7 arcmin",
    ra: 13.4933,
    dec: 47.2,
    image: "images/full/ngc5194.jpg",
    desc: "The Whirlpool Galaxy in Canes Venatici, interacting with NGC 5195."
  },
  {
    id: "NGC 5195",
    name: "Galaxy Companion",
    type: "Dwarf Galaxy",
    mag: 9.6,
    size: "5 arcmin",
    ra: 13.5,
    dec: 47.25,
    image: "images/full/ngc5195.jpg",
    desc: "The small companion galaxy interacting with M51 (Whirlpool)."
  },
  {
    id: "NGC 5236",
    name: "Southern Pinwheel Galaxy",
    type: "Spiral Galaxy",
    mag: 7.6,
    size: "12x11 arcmin",
    ra: 13.6167,
    dec: -29.8667,
    image: "images/full/ngc5236.jpg",
    desc: "A large barred spiral galaxy in Hydra, also known as M83."
  },
  {
    id: "NGC 5248",
    name: "Spiral Galaxy",
    type: "Spiral Galaxy",
    mag: 10.3,
    size: "6.2 arcmin",
    ra: 13.6333,
    dec: 8.8833,
    image: "images/full/ngc5248.jpg",
    desc: "A spiral galaxy in Boötes with bright spiral arms."
  },
  {
    id: "NGC 5363",
    name: "Lenticular Galaxy",
    type: "Galaxy",
    mag: 10.5,
    size: "4 arcmin",
    ra: 13.95,
    dec: 5.15,
    image: "images/full/ngc5363.jpg",
    desc: "A lenticular galaxy in Virgo with some dust lanes."
  },
  {
    id: "NGC 5866",
    name: "Spindle Galaxy",
    type: "Lenticular Galaxy",
    mag: 9.9,
    size: "6x3 arcmin",
    ra: 15.0833,
    dec: 55.7667,
    image: "images/full/ngc5866.jpg",
    desc: "A lenticular galaxy in Draco, candidate for the missing Messier M102."
  },
  {
    id: "NGC 5907",
    name: "Splinter Galaxy",
    type: "Edge-on Spiral Galaxy",
    mag: 10.4,
    size: "12x1.5 arcmin",
    ra: 15.15,
    dec: 56.3333,
    image: "images/full/ngc5907.jpg",
    desc: "A thin edge-on spiral galaxy in Draco, nicknamed the Splinter."
  },
  {
    id: "NGC 598",
    name: "Triangulum Galaxy (M33)",
    type: "Spiral Galaxy",
    mag: 5.7,
    size: "62x37 arcmin",
    ra: 1.55,
    dec: 30.65,
    image: "images/full/ngc598.jpg",
    desc: "Also known as M33, a large spiral galaxy in Triangulum, part of the Local Group."
  },
  {
    id: "NGC 6362",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.5,
    size: "10 arcmin",
    ra: 17.5,
    dec: -67.05,
    image: "images/full/ngc6362.jpg",
    desc: "A bright globular cluster in Ara."
  },
  {
    id: "NGC 6397",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 5.8,
    size: "26 arcmin",
    ra: 17.6833,
    dec: -53.6667,
    image: "images/full/ngc6397.jpg",
    desc: "One of the closest globular clusters to Earth, in Ara."
  },
  {
    id: "NGC 6543",
    name: "Cat’s Eye Nebula",
    type: "Planetary Nebula",
    mag: 8.8,
    size: "0.4 arcmin",
    ra: 17.9667,
    dec: 66.6333,
    image: "images/full/ngc6543.jpg",
    desc: "A famous planetary nebula in Draco with complex structure."
  },
  {
    id: "NGC 6723",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.8,
    size: "12 arcmin",
    ra: 18.9167,
    dec: -36.6333,
    image: "images/full/ngc6723.jpg",
    desc: "A globular cluster in Sagittarius, near the border with Corona Australis."
  },
  {
    id: "NGC 6822",
    name: "Barnard’s Galaxy",
    type: "Irregular Galaxy",
    mag: 9.3,
    size: "15x13 arcmin",
    ra: 19.75,
    dec: -14.8,
    image: "images/full/ngc6822.jpg",
    desc: "A dwarf irregular galaxy in Sagittarius, part of the Local Group."
  },
  {
    id: "NGC 6888",
    name: "Crescent Nebula",
    type: "Emission Nebula",
    mag: 7.4,
    size: "20 arcmin",
    ra: 20.2,
    dec: 38.3667,
    image: "images/full/ngc6888.jpg",
    desc: "A bright emission nebula in Cygnus formed by a Wolf-Rayet star."
  },
  {
    id: "NGC 7006",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 10.6,
    size: "2.8 arcmin",
    ra: 21.1,
    dec: 16.2,
    image: "images/full/ngc7006.jpg",
    desc: "A remote globular cluster in Delphinus, among the most distant known."
  },
  {
    id: "NGC 7009",
    name: "Saturn Nebula",
    type: "Planetary Nebula",
    mag: 8.0,
    size: "0.6 arcmin",
    ra: 21.0667,
    dec: -11.3667,
    image: "images/full/ngc7009.jpg",
    desc: "A planetary nebula in Aquarius, its shape resembles Saturn with rings."
  },
  {
    id: "NGC 7293",
    name: "Helix Nebula",
    type: "Planetary Nebula",
    mag: 7.3,
    size: "16 arcmin",
    ra: 22.5333,
    dec: -20.8333,
    image: "images/full/ngc7293.jpg",
    desc: "A large nearby planetary nebula in Aquarius, nicknamed the Eye of God."
  },
  {
    id: "NGC 7331",
    name: "Deer Lick Galaxy",
    type: "Spiral Galaxy",
    mag: 9.5,
    size: "10.5x3.7 arcmin",
    ra: 22.9667,
    dec: 34.4167,
    image: "images/full/ngc7331.jpg",
    desc: "A large spiral galaxy in Pegasus, similar to the Milky Way."
  },
  {
    id: "NGC 7479",
    name: "Barred Spiral Galaxy",
    type: "Spiral Galaxy",
    mag: 10.9,
    size: "4x3 arcmin",
    ra: 23.05,
    dec: 12.3,
    image: "images/full/ngc7479.jpg",
    desc: "A barred spiral galaxy in Pegasus, sometimes called the Propeller Galaxy."
  },
  {
    id: "NGC 752",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.7,
    size: "50 arcmin",
    ra: 1.9667,
    dec: 37.8333,
    image: "images/full/ngc752.jpg",
    desc: "A large, sparse open cluster in Andromeda."
  },
  {
    id: "NGC 7635",
    name: "Bubble Nebula",
    type: "Emission Nebula",
    mag: 10.0,
    size: "15 arcmin",
    ra: 23.25,
    dec: 61.5833,
    image: "images/full/ngc7635.jpg",
    desc: "A bright nebula in Cassiopeia formed by a massive star’s stellar wind."
  },
  {
    id: "NGC 7662",
    name: "Blue Snowball Nebula",
    type: "Planetary Nebula",
    mag: 8.6,
    size: "0.5 arcmin",
    ra: 23.25,
    dec: 42.5333,
    image: "images/full/ngc7662.jpg",
    desc: "A bright planetary nebula in Andromeda with a bluish hue."
  },
  {
    id: "NGC 7789",
    name: "Caroline’s Rose Cluster",
    type: "Open Cluster",
    mag: 6.7,
    size: "16 arcmin",
    ra: 23.9333,
    dec: 56.7167,
    image: "images/full/ngc7789.jpg",
    desc: "A rich open cluster in Cassiopeia, discovered by Caroline Herschel."
  }
];
