const caldwellCatalog = [
  {
    id: "C1",
    name: "NGC 188",
    type: "Open Cluster",
    mag: 8.1,
    size: "17 arcmin",
    ra: 0.8722,
    dec: 85.25,
    image: "images/full/c1.jpg",
    desc: "One of the oldest known open clusters, located in Cepheus near the north celestial pole."
  },
  {
    id: "C2",
    name: "NGC 40 (Bow-Tie Nebula)",
    type: "Planetary Nebula",
    mag: 10.7,
    size: "1 arcmin",
    ra: 0.9833,
    dec: 72.5167,
    image: "images/full/c2.jpg",
    desc: "A planetary nebula in Cepheus with a bright central star."
  },
  {
    id: "C3",
    name: "NGC 4236",
    type: "Barred Spiral Galaxy",
    mag: 9.6,
    size: "21x7 arcmin",
    ra: 12.3333,
    dec: 69.4667,
    image: "images/full/c3.jpg",
    desc: "A faint barred spiral galaxy in Draco."
  },
  {
    id: "C4",
    name: "NGC 7023 (Iris Nebula)",
    type: "Reflection Nebula",
    mag: 6.8,
    size: "18 arcmin",
    ra: 21.0333,
    dec: 68.1667,
    image: "images/full/c4.jpg",
    desc: "A bright reflection nebula in Cepheus, resembling a flower."
  },
  {
    id: "C5",
    name: "IC 342",
    type: "Spiral Galaxy",
    mag: 9.1,
    size: "20x18 arcmin",
    ra: 3.3167,
    dec: 68.1,
    image: "images/full/c5.jpg",
    desc: "A large spiral galaxy in Camelopardalis, obscured by interstellar dust."
  },
  {
    id: "C6",
    name: "NGC 6543 (Cat's Eye Nebula)",
    type: "Planetary Nebula",
    mag: 8.8,
    size: "0.4 arcmin",
    ra: 17.9667,
    dec: 66.6333,
    image: "images/full/c6.jpg",
    desc: "A bright planetary nebula in Draco with intricate structure."
  },
  {
    id: "C7",
    name: "NGC 2403",
    type: "Spiral Galaxy",
    mag: 8.9,
    size: "22x12 arcmin",
    ra: 7.6333,
    dec: 65.6,
    image: "images/full/c7.jpg",
    desc: "A bright spiral galaxy in Camelopardalis."
  },
  {
    id: "C8",
    name: "NGC 559",
    type: "Open Cluster",
    mag: 9.5,
    size: "5 arcmin",
    ra: 1.4833,
    dec: 63.3333,
    image: "images/full/c8.jpg",
    desc: "A compact open cluster in Cassiopeia."
  },
  {
    id: "C9",
    name: "Cave Nebula (Sh2-155)",
    type: "Diffuse Nebula",
    mag: 7.7,
    size: "50 arcmin",
    ra: 22.5,
    dec: 62.5,
    image: "images/full/c9.jpg",
    desc: "A dark nebula complex in Cepheus with star-forming regions."
  },
  {
    id: "C10",
    name: "NGC 663",
    type: "Open Cluster",
    mag: 7.1,
    size: "16 arcmin",
    ra: 1.75,
    dec: 61.2167,
    image: "images/full/c10.jpg",
    desc: "A rich open cluster in Cassiopeia."
  },
  {
    id: "C11",
    name: "NGC 7635 (Bubble Nebula)",
    type: "Emission Nebula",
    mag: 10.0,
    size: "15 arcmin",
    ra: 23.25,
    dec: 61.5833,
    image: "images/full/c11.jpg",
    desc: "A striking bubble-shaped nebula in Cassiopeia."
  },
  {
    id: "C12",
    name: "NGC 6946 (Fireworks Galaxy)",
    type: "Spiral Galaxy",
    mag: 9.6,
    size: "11.5x10 arcmin",
    ra: 20.5833,
    dec: 60.15,
    image: "images/full/c12.jpg",
    desc: "A spiral galaxy on the border of Cepheus and Cygnus, known for supernovae."
  },
  {
    id: "C13",
    name: "NGC 457 (Owl Cluster)",
    type: "Open Cluster",
    mag: 6.4,
    size: "20 arcmin",
    ra: 1.3167,
    dec: 58.3,
    image: "images/full/c13.jpg",
    desc: "An open cluster in Cassiopeia resembling an owl or E.T."
  },
  {
    id: "C14",
    name: "Double Cluster (NGC 869 & NGC 884)",
    type: "Open Cluster",
    mag: 4.3,
    size: "60 arcmin",
    ra: 2.3333,
    dec: 57.15,
    image: "images/full/c14.jpg",
    desc: "Two adjacent open clusters in Perseus, spectacular in binoculars."
  },
  {
    id: "C15",
    name: "NGC 6826 (Blinking Planetary)",
    type: "Planetary Nebula",
    mag: 8.8,
    size: "0.6 arcmin",
    ra: 19.6167,
    dec: 50.4833,
    image: "images/full/c15.jpg",
    desc: "A planetary nebula in Cygnus that seems to blink when viewed directly."
  },
  {
    id: "C16",
    name: "NGC 7243",
    type: "Open Cluster",
    mag: 6.4,
    size: "21 arcmin",
    ra: 22.3833,
    dec: 49.8667,
    image: "images/full/c16.jpg",
    desc: "A sparse open cluster in Lacerta."
  },
  {
    id: "C17",
    name: "NGC 147",
    type: "Dwarf Galaxy",
    mag: 9.5,
    size: "13x8 arcmin",
    ra: 0.6667,
    dec: 48.5167,
    image: "images/full/c17.jpg",
    desc: "A dwarf spheroidal galaxy in Cassiopeia, companion of M31."
  },
  {
    id: "C18",
    name: "NGC 185",
    type: "Dwarf Galaxy",
    mag: 9.2,
    size: "11x10 arcmin",
    ra: 0.7,
    dec: 48.3333,
    image: "images/full/c18.jpg",
    desc: "A dwarf elliptical galaxy, another satellite of M31."
  },
  {
    id: "C19",
    name: "Cocoon Nebula (IC 5146)",
    type: "Reflection Nebula",
    mag: 10.0,
    size: "12 arcmin",
    ra: 21.8667,
    dec: 47.2667,
    image: "images/full/c19.jpg",
    desc: "A reflection and emission nebula in Cygnus, surrounded by dark nebulae."
  },
  {
    id: "C20",
    name: "NGC 7000 (North America Nebula)",
    type: "Emission Nebula",
    mag: 4.0,
    size: "120 arcmin",
    ra: 20.95,
    dec: 44.3333,
    image: "images/full/c20.jpg",
    desc: "A large nebula in Cygnus, resembling the continent of North America."
  },
  {
    id: "C21",
    name: "NGC 4449",
    type: "Irregular Galaxy",
    mag: 9.4,
    size: "6x4 arcmin",
    ra: 12.5,
    dec: 44.0833,
    image: "images/full/c21.jpg",
    desc: "A Magellanic-type irregular galaxy in Canes Venatici."
  },
  {
    id: "C22",
    name: "NGC 7662 (Blue Snowball Nebula)",
    type: "Planetary Nebula",
    mag: 8.6,
    size: "0.5 arcmin",
    ra: 23.25,
    dec: 42.5333,
    image: "images/full/c22.jpg",
    desc: "A bright planetary nebula in Andromeda with a bluish hue."
  },
  {
    id: "C23",
    name: "NGC 891",
    type: "Edge-on Spiral Galaxy",
    mag: 9.9,
    size: "14x3 arcmin",
    ra: 2.3833,
    dec: 42.3333,
    image: "images/full/c23.jpg",
    desc: "A beautiful edge-on spiral galaxy in Andromeda."
  },
  {
    id: "C24",
    name: "NGC 1275 (Perseus A)",
    type: "Galaxy",
    mag: 12.6,
    size: "2 arcmin",
    ra: 3.3167,
    dec: 41.5167,
    image: "images/full/c24.jpg",
    desc: "A bright galaxy at the center of the Perseus Cluster, strong radio source."
  },
  {
    id: "C25",
    name: "NGC 2419 (Intergalactic Wanderer)",
    type: "Globular Cluster",
    mag: 10.4,
    size: "5 arcmin",
    ra: 7.6167,
    dec: 38.8833,
    image: "images/full/c25.jpg",
    desc: "A remote globular cluster in Lynx, one of the most distant in the Milky Way."
  },
  {
    id: "C26",
    name: "NGC 4244",
    type: "Edge-on Spiral Galaxy",
    mag: 10.4,
    size: "17x2 arcmin",
    ra: 12.3,
    dec: 37.8,
    image: "images/full/c26.jpg",
    desc: "A thin edge-on spiral galaxy in Canes Venatici."
  },
  {
    id: "C27",
    name: "NGC 6888 (Crescent Nebula)",
    type: "Emission Nebula",
    mag: 7.4,
    size: "20 arcmin",
    ra: 20.2,
    dec: 38.3667,
    image: "images/full/c27.jpg",
    desc: "A bright emission nebula in Cygnus formed by a Wolf-Rayet star."
  },
  {
    id: "C28",
    name: "NGC 752",
    type: "Open Cluster",
    mag: 5.7,
    size: "50 arcmin",
    ra: 1.9667,
    dec: 37.8333,
    image: "images/full/c28.jpg",
    desc: "A large scattered open cluster in Andromeda."
  },
  {
    id: "C29",
    name: "NGC 5005",
    type: "Spiral Galaxy",
    mag: 9.8,
    size: "5x3 arcmin",
    ra: 13.05,
    dec: 37.0333,
    image: "images/full/c29.jpg",
    desc: "A spiral galaxy in Canes Venatici."
  },
  {
    id: "C30",
    name: "NGC 7331",
    type: "Spiral Galaxy",
    mag: 9.5,
    size: "10.5x3.7 arcmin",
    ra: 22.9667,
    dec: 34.4167,
    image: "images/full/c30.jpg",
    desc: "A large spiral galaxy in Pegasus, sometimes called the Deer Lick Galaxy."
  },
  {
    id: "C31",
    name: "IC 405 (Flaming Star Nebula)",
    type: "Emission Nebula",
    mag: 6.0,
    size: "30 arcmin",
    ra: 5.1667,
    dec: 34.25,
    image: "images/full/c31.jpg",
    desc: "A bright emission/reflection nebula in Auriga."
  },
  {
    id: "C32",
    name: "NGC 4631 (Whale Galaxy)",
    type: "Spiral Galaxy",
    mag: 9.3,
    size: "15x3 arcmin",
    ra: 12.6167,
    dec: 32.1333,
    image: "images/full/c32.jpg",
    desc: "A spiral galaxy in Canes Venatici, resembles a whale."
  },
  {
    id: "C33",
    name: "NGC 6992 (Eastern Veil Nebula)",
    type: "Supernova Remnant",
    mag: 7.0,
    size: "70 arcmin",
    ra: 20.9333,
    dec: 31.75,
    image: "images/full/c33.jpg",
    desc: "Part of the Veil Nebula in Cygnus, a bright supernova remnant filament."
  },
  {
    id: "C34",
    name: "NGC 6960 (Western Veil Nebula)",
    type: "Supernova Remnant",
    mag: 7.0,
    size: "70 arcmin",
    ra: 20.7833,
    dec: 30.7,
    image: "images/full/c34.jpg",
    desc: "Another section of the Veil Nebula, passing through the star 52 Cygni."
  },
  {
    id: "C35",
    name: "NGC 4889",
    type: "Elliptical Galaxy",
    mag: 11.4,
    size: "3 arcmin",
    ra: 13.0167,
    dec: 27.9833,
    image: "images/full/c35.jpg",
    desc: "A giant elliptical galaxy in Coma Berenices, central to the Coma Cluster."
  },
  {
    id: "C36",
    name: "NGC 4559",
    type: "Spiral Galaxy",
    mag: 9.9,
    size: "10.7x5 arcmin",
    ra: 12.6167,
    dec: 27.9667,
    image: "images/full/c36.jpg",
    desc: "A spiral galaxy in Coma Berenices."
  },
  {
    id: "C37",
    name: "NGC 6885",
    type: "Open Cluster",
    mag: 5.7,
    size: "20 arcmin",
    ra: 20.2,
    dec: 26.6167,
    image: "images/full/c37.jpg",
    desc: "An open cluster in Vulpecula, near the Dumbbell Nebula."
  },
  {
    id: "C38",
    name: "NGC 4565 (Needle Galaxy)",
    type: "Edge-on Spiral Galaxy",
    mag: 9.6,
    size: "15.9x1.9 arcmin",
    ra: 12.6167,
    dec: 25.9833,
    image: "images/full/c38.jpg",
    desc: "A striking edge-on spiral galaxy in Coma Berenices."
  },
  {
    id: "C39",
    name: "NGC 2392 (Eskimo Nebula)",
    type: "Planetary Nebula",
    mag: 9.2,
    size: "0.8 arcmin",
    ra: 7.4,
    dec: 20.9167,
    image: "images/full/c39.jpg",
    desc: "A planetary nebula in Gemini, nicknamed the Clownface Nebula."
  },
  {
    id: "C40",
    name: "NGC 3626",
    type: "Spiral Galaxy",
    mag: 11.5,
    size: "2.9x1.8 arcmin",
    ra: 11.3833,
    dec: 18.35,
    image: "images/full/c40.jpg",
    desc: "A spiral galaxy in Leo."
  },
  {
    id: "C41",
    name: "Hyades Cluster",
    type: "Open Cluster",
    mag: 0.5,
    size: "330 arcmin",
    ra: 4.45,
    dec: 15.95,
    image: "images/full/c41.jpg",
    desc: "The nearest open cluster to Earth, in Taurus, forming a V-shape."
  },
  {
    id: "C42",
    name: "NGC 7006",
    type: "Globular Cluster",
    mag: 10.6,
    size: "2.8 arcmin",
    ra: 21.1,
    dec: 16.2,
    image: "images/full/c42.jpg",
    desc: "A remote globular cluster in Delphinus, one of the most distant."
  },
  {
    id: "C43",
    name: "NGC 7814 (Little Sombrero)",
    type: "Edge-on Spiral Galaxy",
    mag: 10.6,
    size: "5.5x2.3 arcmin",
    ra: 0.05,
    dec: 16.1667,
    image: "images/full/c43.jpg",
    desc: "An edge-on spiral galaxy in Pegasus, resembles M104."
  },
  {
    id: "C44",
    name: "NGC 7479",
    type: "Barred Spiral Galaxy",
    mag: 10.9,
    size: "4x3 arcmin",
    ra: 23.05,
    dec: 12.3,
    image: "images/full/c44.jpg",
    desc: "A barred spiral galaxy in Pegasus, sometimes called the Propeller Galaxy."
  },
  {
    id: "C45",
    name: "NGC 5248",
    type: "Spiral Galaxy",
    mag: 10.3,
    size: "6.2 arcmin",
    ra: 13.6333,
    dec: 8.8833,
    image: "images/full/c45.jpg",
    desc: "A spiral galaxy in Boötes."
  },
  {
    id: "C46",
    name: "NGC 2261 (Hubble's Variable Nebula)",
    type: "Reflection Nebula",
    mag: 9.0,
    size: "2x1 arcmin",
    ra: 6.0833,
    dec: 8.4833,
    image: "images/full/c46.jpg",
    desc: "A reflection nebula in Monoceros that varies in brightness."
  },
  {
    id: "C47",
    name: "NGC 6934",
    type: "Globular Cluster",
    mag: 8.9,
    size: "5 arcmin",
    ra: 20.45,
    dec: 7.4,
    image: "images/full/c47.jpg",
    desc: "A globular cluster in Delphinus."
  },
  {
    id: "C48",
    name: "NGC 2775",
    type: "Spiral Galaxy",
    mag: 10.2,
    size: "4.3 arcmin",
    ra: 9.1,
    dec: 7.0333,
    image: "images/full/c48.jpg",
    desc: "A spiral galaxy in Cancer with tightly wound arms."
  },
  {
    id: "C49",
    name: "NGC 2237 (Rosette Nebula)",
    type: "Emission Nebula",
    mag: 9.0,
    size: "80 arcmin",
    ra: 6.5,
    dec: 5.0,
    image: "images/full/c49.jpg",
    desc: "A large emission nebula in Monoceros, shaped like a rosette."
  },
  {
    id: "C50",
    name: "NGC 2244",
    type: "Open Cluster",
    mag: 4.8,
    size: "24 arcmin",
    ra: 6.5,
    dec: 5.0,
    image: "images/full/c50.jpg",
    desc: "The open cluster at the center of the Rosette Nebula."
  },
  {
    id: "C51",
    name: "IC 1613",
    type: "Dwarf Galaxy",
    mag: 9.9,
    size: "16x14 arcmin",
    ra: 1.0833,
    dec: 2.1333,
    image: "images/full/c51.jpg",
    desc: "A Local Group dwarf galaxy in Cetus."
  },
  {
    id: "C52",
    name: "NGC 4697",
    type: "Elliptical Galaxy",
    mag: 9.2,
    size: "7.4 arcmin",
    ra: 12.8,
    dec: -5.8,
    image: "images/full/c52.jpg",
    desc: "An elliptical galaxy in Virgo."
  },
  {
    id: "C53",
    name: "NGC 3115 (Spindle Galaxy)",
    type: "Lenticular Galaxy",
    mag: 9.2,
    size: "7.2x2.5 arcmin",
    ra: 10.05,
    dec: -7.7167,
    image: "images/full/c53.jpg",
    desc: "A bright lenticular galaxy in Sextans."
  },
  {
    id: "C54",
    name: "NGC 2506",
    type: "Open Cluster",
    mag: 7.6,
    size: "12 arcmin",
    ra: 8.0,
    dec: -10.8,
    image: "images/full/c54.jpg",
    desc: "An open cluster in Monoceros."
  },
  {
    id: "C55",
    name: "NGC 7009 (Saturn Nebula)",
    type: "Planetary Nebula",
    mag: 8.0,
    size: "0.6 arcmin",
    ra: 21.0667,
    dec: -11.3667,
    image: "images/full/c55.jpg",
    desc: "A planetary nebula in Aquarius, resembling the planet Saturn."
  },
  {
    id: "C56",
    name: "NGC 246 (Skull Nebula)",
    type: "Planetary Nebula",
    mag: 8.0,
    size: "3.8 arcmin",
    ra: 0.8333,
    dec: -11.8,
    image: "images/full/c56.jpg",
    desc: "A planetary nebula in Cetus."
  },
  {
    id: "C57",
    name: "NGC 6822 (Barnard's Galaxy)",
    type: "Irregular Galaxy",
    mag: 9.3,
    size: "15x13 arcmin",
    ra: 19.75,
    dec: -14.8,
    image: "images/full/c57.jpg",
    desc: "A dwarf irregular galaxy in Sagittarius, part of the Local Group."
  },
  {
    id: "C58",
    name: "NGC 2360 (Caroline’s Cluster)",
    type: "Open Cluster",
    mag: 7.2,
    size: "13 arcmin",
    ra: 7.0333,
    dec: -15.6333,
    image: "images/full/c58.jpg",
    desc: "An open cluster in Canis Major discovered by Caroline Herschel."
  },
  {
    id: "C59",
    name: "NGC 3242 (Ghost of Jupiter)",
    type: "Planetary Nebula",
    mag: 8.6,
    size: "0.5 arcmin",
    ra: 10.25,
    dec: -18.65,
    image: "images/full/c59.jpg",
    desc: "A planetary nebula in Hydra resembling Jupiter’s disk."
  },
  {
    id: "C60",
    name: "NGC 4038/4039 (Antennae Galaxies)",
    type: "Interacting Galaxies",
    mag: 10.3,
    size: "5 arcmin",
    ra: 12.3333,
    dec: -18.8667,
    image: "images/full/c60.jpg",
    desc: "A pair of colliding galaxies in Corvus."
  },
  {
    id: "C61",
    name: "NGC 2362 (Tau Canis Majoris Cluster)",
    type: "Open Cluster",
    mag: 4.1,
    size: "8 arcmin",
    ra: 7.0,
    dec: -24.9,
    image: "images/full/c61.jpg",
    desc: "A compact open cluster around Tau Canis Majoris."
  },
  {
    id: "C62",
    name: "NGC 2477",
    type: "Open Cluster",
    mag: 5.8,
    size: "27 arcmin",
    ra: 7.9167,
    dec: -38.5167,
    image: "images/full/c62.jpg",
    desc: "A rich open cluster in Puppis."
  },
  {
    id: "C63",
    name: "NGC 7293 (Helix Nebula)",
    type: "Planetary Nebula",
    mag: 7.3,
    size: "16 arcmin",
    ra: 22.5333,
    dec: -20.8333,
    image: "images/full/c63.jpg",
    desc: "A large nearby planetary nebula in Aquarius, also called the Eye of God."
  },
  {
    id: "C64",
    name: "NGC 2367",
    type: "Open Cluster",
    mag: 7.2,
    size: "7 arcmin",
    ra: 7.05,
    dec: -21.0,
    image: "images/full/c64.jpg",
    desc: "A small open cluster in Canis Major."
  },
  {
    id: "C65",
    name: "NGC 253 (Sculptor Galaxy)",
    type: "Spiral Galaxy",
    mag: 7.1,
    size: "27x7 arcmin",
    ra: 0.7917,
    dec: -25.2833,
    image: "images/full/c65.jpg",
    desc: "A bright spiral galaxy in Sculptor, also called the Silver Coin Galaxy."
  },
  {
    id: "C66",
    name: "NGC 5694",
    type: "Globular Cluster",
    mag: 10.2,
    size: "3.6 arcmin",
    ra: 14.5667,
    dec: -26.5333,
    image: "images/full/c66.jpg",
    desc: "A faint globular cluster in Hydra."
  },
  {
    id: "C67",
    name: "NGC 1097",
    type: "Barred Spiral Galaxy",
    mag: 9.2,
    size: "9.3x6.3 arcmin",
    ra: 2.75,
    dec: -30.2833,
    image: "images/full/c67.jpg",
    desc: "A barred spiral galaxy in Fornax with prominent dust lanes."
  },
  {
    id: "C68",
    name: "NGC 6729",
    type: "Reflection Nebula",
    mag: 9.1,
    size: "2 arcmin",
    ra: 19.3,
    dec: -36.9667,
    image: "images/full/c68.jpg",
    desc: "A reflection nebula in Corona Australis."
  },
  {
    id: "C69",
    name: "NGC 6302 (Bug Nebula)",
    type: "Planetary Nebula",
    mag: 9.6,
    size: "1 arcmin",
    ra: 17.9667,
    dec: -37.1167,
    image: "images/full/c69.jpg",
    desc: "A planetary nebula in Scorpius with a bipolar shape."
  },
  {
    id: "C70",
    name: "NGC 300",
    type: "Spiral Galaxy",
    mag: 8.1,
    size: "22x15 arcmin",
    ra: 0.9167,
    dec: -37.6833,
    image: "images/full/c70.jpg",
    desc: "A bright spiral galaxy in Sculptor, part of the Sculptor Group."
  },
  {
    id: "C71",
    name: "NGC 247",
    type: "Spiral Galaxy",
    mag: 9.1,
    size: "21x7 arcmin",
    ra: 0.8667,
    dec: -20.75,
    image: "images/full/c71.jpg",
    desc: "A spiral galaxy in Cetus, part of the Sculptor Group."
  },
  {
    id: "C72",
    name: "NGC 55",
    type: "Irregular Galaxy",
    mag: 8.4,
    size: "32x5 arcmin",
    ra: 0.2167,
    dec: -39.25,
    image: "images/full/c72.jpg",
    desc: "A barred irregular galaxy in Sculptor."
  },
  {
    id: "C73",
    name: "NGC 1851",
    type: "Globular Cluster",
    mag: 7.3,
    size: "11 arcmin",
    ra: 5.1,
    dec: -40.05,
    image: "images/full/c73.jpg",
    desc: "A compact globular cluster in Columba."
  },
  {
    id: "C74",
    name: "NGC 3132 (Eight-Burst Nebula)",
    type: "Planetary Nebula",
    mag: 9.9,
    size: "0.8 arcmin",
    ra: 10.1167,
    dec: -40.4333,
    image: "images/full/c74.jpg",
    desc: "A planetary nebula in Vela, sometimes called the Southern Ring."
  },
  {
    id: "C75",
    name: "NGC 6124",
    type: "Open Cluster",
    mag: 5.8,
    size: "29 arcmin",
    ra: 16.3333,
    dec: -40.65,
    image: "images/full/c75.jpg",
    desc: "A bright open cluster in Scorpius."
  },
  {
    id: "C76",
    name: "NGC 6231",
    type: "Open Cluster",
    mag: 2.6,
    size: "15 arcmin",
    ra: 16.9,
    dec: -41.8,
    image: "images/full/c76.jpg",
    desc: "A very bright open cluster in Scorpius, visible to the naked eye."
  },
  {
    id: "C77",
    name: "NGC 5128 (Centaurus A)",
    type: "Radio Galaxy",
    mag: 6.8,
    size: "25x20 arcmin",
    ra: 13.4167,
    dec: -43.0167,
    image: "images/full/c77.jpg",
    desc: "A peculiar radio galaxy in Centaurus with a dark dust lane."
  },
  {
    id: "C78",
    name: "NGC 6541",
    type: "Globular Cluster",
    mag: 6.3,
    size: "15 arcmin",
    ra: 18.0833,
    dec: -43.7167,
    image: "images/full/c78.jpg",
    desc: "A bright globular cluster in Corona Australis."
  },
  {
    id: "C79",
    name: "NGC 3201",
    type: "Globular Cluster",
    mag: 8.2,
    size: "18 arcmin",
    ra: 10.2833,
    dec: -46.4167,
    image: "images/full/c79.jpg",
    desc: "A large, loose globular cluster in Vela."
  },
  {
    id: "C80",
    name: "NGC 5139 (Omega Centauri)",
    type: "Globular Cluster",
    mag: 3.7,
    size: "36 arcmin",
    ra: 13.45,
    dec: -47.4667,
    image: "images/full/c80.jpg",
    desc: "The largest and brightest globular cluster in the sky, in Centaurus."
  },
  {
    id: "C81",
    name: "NGC 6352",
    type: "Globular Cluster",
    mag: 7.8,
    size: "7.1 arcmin",
    ra: 17.4833,
    dec: -48.4333,
    image: "images/full/c81.jpg",
    desc: "A globular cluster in Ara."
  },
  {
    id: "C82",
    name: "NGC 6193",
    type: "Open Cluster",
    mag: 5.2,
    size: "15 arcmin",
    ra: 16.7167,
    dec: -48.7667,
    image: "images/full/c82.jpg",
    desc: "A bright open cluster in Ara, associated with nebulosity."
  },
  {
    id: "C83",
    name: "NGC 4945",
    type: "Spiral Galaxy",
    mag: 8.6,
    size: "20x4 arcmin",
    ra: 13.05,
    dec: -49.4667,
    image: "images/full/c83.jpg",
    desc: "A large edge-on spiral galaxy in Centaurus."
  },
  {
    id: "C84",
    name: "NGC 5286",
    type: "Globular Cluster",
    mag: 7.3,
    size: "9 arcmin",
    ra: 13.7333,
    dec: -51.3667,
    image: "images/full/c84.jpg",
    desc: "A globular cluster in Centaurus."
  },
  {
    id: "C85",
    name: "IC 2391 (Omicron Velorum Cluster)",
    type: "Open Cluster",
    mag: 2.5,
    size: "50 arcmin",
    ra: 8.4,
    dec: -53.0333,
    image: "images/full/c85.jpg",
    desc: "A bright open cluster in Vela."
  },
  {
    id: "C86",
    name: "NGC 6397",
    type: "Globular Cluster",
    mag: 5.8,
    size: "26 arcmin",
    ra: 17.6833,
    dec: -53.6667,
    image: "images/full/c86.jpg",
    desc: "One of the nearest globular clusters, in Ara."
  },
  {
    id: "C87",
    name: "NGC 1261",
    type: "Globular Cluster",
    mag: 8.3,
    size: "9 arcmin",
    ra: 3.2,
    dec: -55.2167,
    image: "images/full/c87.jpg",
    desc: "A globular cluster in Horologium."
  },
  {
    id: "C88",
    name: "NGC 5823",
    type: "Open Cluster",
    mag: 7.9,
    size: "12 arcmin",
    ra: 15.0833,
    dec: -55.6,
    image: "images/full/c88.jpg",
    desc: "A loose open cluster in Circinus."
  },
  {
    id: "C89",
    name: "NGC 6067",
    type: "Open Cluster",
    mag: 5.6,
    size: "14 arcmin",
    ra: 16.1833,
    dec: -54.2167,
    image: "images/full/c89.jpg",
    desc: "A rich open cluster in Norma."
  },
  {
    id: "C90",
    name: "NGC 2867",
    type: "Planetary Nebula",
    mag: 9.7,
    size: "0.3 arcmin",
    ra: 9.4,
    dec: -58.3,
    image: "images/full/c90.jpg",
    desc: "A planetary nebula in Carina."
  },
  {
    id: "C91",
    name: "NGC 3532 (Wishing Well Cluster)",
    type: "Open Cluster",
    mag: 3.0,
    size: "55 arcmin",
    ra: 11.0,
    dec: -58.75,
    image: "images/full/c91.jpg",
    desc: "A large bright open cluster in Carina, nicknamed the Wishing Well."
  },
  {
    id: "C92",
    name: "NGC 3372 (Eta Carinae Nebula)",
    type: "Emission Nebula",
    mag: 1.0,
    size: "120 arcmin",
    ra: 10.75,
    dec: -59.6833,
    image: "images/full/c92.jpg",
    desc: "A massive emission nebula in Carina, home to Eta Carinae."
  },
  {
    id: "C93",
    name: "NGC 6752",
    type: "Globular Cluster",
    mag: 5.4,
    size: "20 arcmin",
    ra: 19.0333,
    dec: -59.9833,
    image: "images/full/c93.jpg",
    desc: "A bright globular cluster in Pavo."
  },
  {
    id: "C94",
    name: "NGC 4755 (Jewel Box Cluster)",
    type: "Open Cluster",
    mag: 4.2,
    size: "10 arcmin",
    ra: 12.7833,
    dec: -60.35,
    image: "images/full/c94.jpg",
    desc: "A colorful open cluster in Crux."
  },
  {
    id: "C95",
    name: "NGC 6025",
    type: "Open Cluster",
    mag: 5.1,
    size: "12 arcmin",
    ra: 16.1,
    dec: -60.4167,
    image: "images/full/c95.jpg",
    desc: "A bright open cluster in Triangulum Australe."
  },
  {
    id: "C96",
    name: "NGC 2516",
    type: "Open Cluster",
    mag: 3.8,
    size: "30 arcmin",
    ra: 7.9667,
    dec: -60.7667,
    image: "images/full/c96.jpg",
    desc: "A bright open cluster in Carina."
  },
  {
    id: "C97",
    name: "NGC 3766",
    type: "Open Cluster",
    mag: 5.3,
    size: "12 arcmin",
    ra: 11.6167,
    dec: -61.6167,
    image: "images/full/c97.jpg",
    desc: "An open cluster in Centaurus known as the Pearl Cluster."
  },
  {
    id: "C98",
    name: "NGC 4609",
    type: "Open Cluster",
    mag: 6.9,
    size: "6 arcmin",
    ra: 12.7167,
    dec: -62.9667,
    image: "images/full/c98.jpg",
    desc: "A small open cluster in Crux."
  },
  {
    id: "C99",
    name: "NGC 3372 (Homunculus Nebula)",
    type: "Reflection Nebula",
    mag: 8.0,
    size: "18 arcsec",
    ra: 10.75,
    dec: -59.6833,
    image: "images/full/c99.jpg",
    desc: "A bipolar nebula around Eta Carinae."
  },
  {
    id: "C100",
    name: "IC 2944 (Running Chicken Nebula)",
    type: "Emission Nebula",
    mag: 4.5,
    size: "70 arcmin",
    ra: 11.75,
    dec: -63.0,
    image: "images/full/c100.jpg",
    desc: "An emission nebula in Centaurus."
  },
  {
    id: "C101",
    name: "NGC 6744",
    type: "Spiral Galaxy",
    mag: 8.3,
    size: "20x12 arcmin",
    ra: 19.0,
    dec: -63.85,
    image: "images/full/c101.jpg",
    desc: "A large spiral galaxy in Pavo, similar to the Milky Way."
  },
  {
    id: "C102",
    name: "NGC 2070 (Tarantula Nebula)",
    type: "Emission Nebula",
    mag: 8.0,
    size: "40 arcmin",
    ra: 5.6333,
    dec: -69.0833,
    image: "images/full/c102.jpg",
    desc: "A giant star-forming region in the Large Magellanic Cloud."
  },
  {
    id: "C103",
    name: "NGC 1850",
    type: "Open Cluster + Nebula",
    mag: 9.0,
    size: "3 arcmin",
    ra: 5.1,
    dec: -68.75,
    image: "images/full/c103.jpg",
    desc: "A young cluster with surrounding nebulosity in the LMC."
  },
  {
    id: "C104",
    name: "NGC 362",
    type: "Globular Cluster",
    mag: 6.4,
    size: "12 arcmin",
    ra: 1.05,
    dec: -70.85,
    image: "images/full/c104.jpg",
    desc: "A globular cluster in Tucana, near the SMC."
  },
  {
    id: "C105",
    name: "NGC 4833",
    type: "Globular Cluster",
    mag: 7.4,
    size: "13 arcmin",
    ra: 12.95,
    dec: -70.8833,
    image: "images/full/c105.jpg",
    desc: "A globular cluster in Musca."
  },
  {
    id: "C106",
    name: "NGC 104 (47 Tucanae)",
    type: "Globular Cluster",
    mag: 4.1,
    size: "30 arcmin",
    ra: 0.6667,
    dec: -72.0833,
    image: "images/full/c106.jpg",
    desc: "A massive globular cluster in Tucana, second only to Omega Centauri."
  },
  {
    id: "C107",
    name: "NGC 6101",
    type: "Globular Cluster",
    mag: 9.3,
    size: "10 arcmin",
    ra: 16.35,
    dec: -72.2,
    image: "images/full/c107.jpg",
    desc: "A faint globular cluster in Apus."
  },
  {
    id: "C108",
    name: "NGC 4372",
    type: "Globular Cluster",
    mag: 7.8,
    size: "18 arcmin",
    ra: 12.4667,
    dec: -72.65,
    image: "images/full/c108.jpg",
    desc: "A globular cluster in Musca, heavily reddened by dust."
  },
  {
    id: "C109",
    name: "NGC 3195",
    type: "Planetary Nebula",
    mag: 11.6,
    size: "1 arcmin",
    ra: 10.1833,
    dec: -80.85,
    image: "images/full/c109.jpg",
    desc: "A planetary nebula in Chamaeleon, one of the southernmost Caldwell objects."
  }
];
