const messierCatalog = [
  {
    id: "M1",
    name: "Crab Nebula",
    type: "Supernova Remnant",
    mag: 8.4,
    size: "6x4 arcmin",
    ra: 5.5756,
    dec: 22.0145,
    image: "images/full/m1.jpg",
    desc: "The remnant of a supernova observed in 1054 AD, located in Taurus."
  },
  {
    id: "M2",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.5,
    size: "16 arcmin",
    ra: 21.5394,
    dec: -0.8233,
    image: "images/full/m2.jpg",
    desc: "A rich, compact cluster of stars in Aquarius, one of the largest known."
  },
  {
    id: "M3",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.2,
    size: "18 arcmin",
    ra: 13.7031,
    dec: 28.376,
    image: "images/full/m3.jpg",
    desc: "Contains around half a million stars, located in Canes Venatici."
  },
  {
    id: "M4",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 5.9,
    size: "26 arcmin",
    ra: 16.4117,
    dec: -26.525,
    image: "images/full/m4.jpg",
    desc: "A loose globular cluster near Antares in Scorpius."
  },
  {
    id: "M5",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 5.7,
    size: "23 arcmin",
    ra: 15.3083,
    dec: 2.0819,
    image: "images/full/m5.jpg",
    desc: "One of the largest globular clusters, visible with binoculars."
  },
  {
    id: "M6",
    name: "Butterfly Cluster",
    type: "Open Cluster",
    mag: 4.2,
    size: "25 arcmin",
    ra: 17.6706,
    dec: -32.2528,
    image: "images/full/m6.jpg",
    desc: "A bright open cluster in Scorpius, named for its butterfly shape."
  },
  {
    id: "M7",
    name: "Ptolemy Cluster",
    type: "Open Cluster",
    mag: 3.3,
    size: "80 arcmin",
    ra: 17.8967,
    dec: -34.8,
    image: "images/full/m7.jpg",
    desc: "A very large open cluster in Scorpius, easily visible to the naked eye."
  },
  {
    id: "M8",
    name: "Lagoon Nebula",
    type: "Diffuse Nebula",
    mag: 6.0,
    size: "90x40 arcmin",
    ra: 18.05,
    dec: -24.3833,
    image: "images/full/m8.jpg",
    desc: "A vast star-forming region in Sagittarius, visible in binoculars."
  },
  {
    id: "M9",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.9,
    size: "9 arcmin",
    ra: 17.3111,
    dec: -18.5167,
    image: "images/full/m9.jpg",
    desc: "A compact cluster near the galactic bulge in Ophiuchus."
  },
  {
    id: "M10",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.6,
    size: "20 arcmin",
    ra: 16.9578,
    dec: -4.1006,
    image: "images/full/m10.jpg",
    desc: "A bright cluster in Ophiuchus, easy with binoculars."
  },
  {
    id: "M11",
    name: "Wild Duck Cluster",
    type: "Open Cluster",
    mag: 5.8,
    size: "14 arcmin",
    ra: 18.8517,
    dec: -6.27,
    image: "images/full/m11.jpg",
    desc: "A dense cluster in Scutum, named for its V-shape like a flock of ducks."
  },
  {
    id: "M12",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.7,
    size: "16 arcmin",
    ra: 16.7878,
    dec: -1.9489,
    image: "images/full/m12.jpg",
    desc: "A relatively loose globular cluster in Ophiuchus."
  },
  {
    id: "M13",
    name: "Hercules Cluster",
    type: "Globular Cluster",
    mag: 5.8,
    size: "20 arcmin",
    ra: 16.6956,
    dec: 36.4611,
    image: "images/full/m13.jpg",
    desc: "The famous Hercules Cluster, visible even to the naked eye under dark skies."
  },
  {
    id: "M14",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.6,
    size: "12 arcmin",
    ra: 17.6261,
    dec: -3.245,
    image: "images/full/m14.jpg",
    desc: "A compact cluster in Ophiuchus."
  },
  {
    id: "M15",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.2,
    size: "12 arcmin",
    ra: 21.5,
    dec: 12.1667,
    image: "images/full/m15.jpg",
    desc: "A dense globular cluster in Pegasus, home to many variable stars."
  },
  {
    id: "M16",
    name: "Eagle Nebula",
    type: "Diffuse Nebula",
    mag: 6.0,
    size: "35x28 arcmin",
    ra: 18.3133,
    dec: -13.8067,
    image: "images/full/m16.jpg",
    desc: "Famous for the Pillars of Creation, a star-forming region in Serpens."
  },
  {
    id: "M17",
    name: "Omega Nebula",
    type: "Diffuse Nebula",
    mag: 6.0,
    size: "20 arcmin",
    ra: 18.3133,
    dec: -16.1719,
    image: "images/full/m17.jpg",
    desc: "Also called the Swan Nebula, a bright H II region in Sagittarius."
  },
  {
    id: "M18",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 7.5,
    size: "9 arcmin",
    ra: 18.3333,
    dec: -17.1,
    image: "images/full/m18.jpg",
    desc: "A small cluster in Sagittarius between the Lagoon and Omega Nebulae."
  },
  {
    id: "M19",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.8,
    size: "17 arcmin",
    ra: 17.0431,
    dec: -26.2678,
    image: "images/full/m19.jpg",
    desc: "One of the most oblate globular clusters, distorted by tidal forces."
  },
  {
    id: "M20",
    name: "Trifid Nebula",
    type: "Diffuse Nebula",
    mag: 6.3,
    size: "28 arcmin",
    ra: 18.0417,
    dec: -23.017,
    image: "images/full/m20.jpg",
    desc: "A bright nebula in Sagittarius, divided into three parts by dark lanes."
  },
  {
    id: "M21",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 6.5,
    size: "13 arcmin",
    ra: 18.0508,
    dec: -22.5,
    image: "images/full/m21.jpg",
    desc: "A small open cluster near the Trifid Nebula."
  },
  {
    id: "M22",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 5.1,
    size: "32 arcmin",
    ra: 18.605,
    dec: -23.9047,
    image: "images/full/m22.jpg",
    desc: "One of the brightest globular clusters in Sagittarius."
  },
  {
    id: "M23",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.5,
    size: "27 arcmin",
    ra: 17.95,
    dec: -19.0167,
    image: "images/full/m23.jpg",
    desc: "A scattered cluster of stars in Sagittarius."
  },
  {
    id: "M24",
    name: "Sagittarius Star Cloud",
    type: "Star Cloud",
    mag: 4.6,
    size: "90 arcmin",
    ra: 18.2917,
    dec: -18.55,
    image: "images/full/m24.jpg",
    desc: "A dense part of the Milky Way rich in stars."
  },
  {
    id: "M25",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 4.6,
    size: "32 arcmin",
    ra: 18.5292,
    dec: -19.25,
    image: "images/full/m25.jpg",
    desc: "A bright open cluster in Sagittarius."
  },
  {
    id: "M26",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 8.0,
    size: "15 arcmin",
    ra: 18.75,
    dec: -9.3833,
    image: "images/full/m26.jpg",
    desc: "A compact open cluster in Scutum."
  },
  {
    id: "M27",
    name: "Dumbbell Nebula",
    type: "Planetary Nebula",
    mag: 7.5,
    size: "8 arcmin",
    ra: 19.9931,
    dec: 22.7219,
    image: "images/full/m27.jpg",
    desc: "A famous planetary nebula in Vulpecula, bright and large."
  },
  {
    id: "M28",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.9,
    size: "11 arcmin",
    ra: 18.4,
    dec: -24.8667,
    image: "images/full/m28.jpg",
    desc: "A compact globular cluster in Sagittarius."
  },
  {
    id: "M29",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 7.1,
    size: "7 arcmin",
    ra: 20.4003,
    dec: 38.5339,
    image: "images/full/m29.jpg",
    desc: "A small open cluster in Cygnus."
  },
  {
    id: "M30",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.2,
    size: "12 arcmin",
    ra: 21.6711,
    dec: -23.1794,
    image: "images/full/m30.jpg",
    desc: "A globular cluster in Capricornus."
  },
  {
    id: "M31",
    name: "Andromeda Galaxy",
    type: "Galaxy",
    mag: 3.4,
    size: "178x63 arcmin",
    ra: 0.7167,
    dec: 41.269,
    image: "images/full/m31.jpg",
    desc: "Nearest spiral galaxy to the Milky Way, visible to the naked eye in dark skies."
  },
  {
    id: "M32",
    name: "Dwarf Elliptical Galaxy",
    type: "Galaxy",
    mag: 8.1,
    size: "8x6 arcmin",
    ra: 0.7117,
    dec: 40.8667,
    image: "images/full/m32.jpg",
    desc: "A dwarf elliptical galaxy, satellite of M31."
  },
  {
    id: "M33",
    name: "Triangulum Galaxy",
    type: "Galaxy",
    mag: 5.7,
    size: "62x39 arcmin",
    ra: 1.5458,
    dec: 30.6583,
    image: "images/full/m33.jpg",
    desc: "A face-on spiral galaxy in Triangulum, part of the Local Group."
  },
  {
    id: "M34",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.5,
    size: "35 arcmin",
    ra: 2.71,
    dec: 42.7833,
    image: "images/full/m34.jpg",
    desc: "A rich open cluster in Perseus."
  },
  {
    id: "M35",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.1,
    size: "28 arcmin",
    ra: 6.1478,
    dec: 24.3339,
    image: "images/full/m35.jpg",
    desc: "A large open cluster in Gemini, visible with binoculars."
  },
  {
    id: "M36",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 6.0,
    size: "12 arcmin",
    ra: 5.6042,
    dec: 34.1333,
    image: "images/full/m36.jpg",
    desc: "An open cluster in Auriga, one of a trio with M37 and M38."
  },
  {
    id: "M37",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.6,
    size: "24 arcmin",
    ra: 5.8717,
    dec: 32.55,
    image: "images/full/m37.jpg",
    desc: "The richest and brightest open cluster in Auriga."
  },
  {
    id: "M38",
    name: "Starfish Cluster",
    type: "Open Cluster",
    mag: 7.0,
    size: "20 arcmin",
    ra: 5.4786,
    dec: 35.85,
    image: "images/full/m38.jpg",
    desc: "A starfish-shaped open cluster in Auriga."
  },
  {
    id: "M39",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 4.6,
    size: "32 arcmin",
    ra: 21.53,
    dec: 48.4333,
    image: "images/full/m39.jpg",
    desc: "A bright but sparse open cluster in Cygnus."
  },
  {
    id: "M40",
    name: "Winnecke 4",
    type: "Double Star",
    mag: 9.6,
    size: "1 arcmin",
    ra: 12.365,
    dec: 58.0833,
    image: "images/full/m40.jpg",
    desc: "A double star in Ursa Major, not a true deep-sky object."
  },
  {
    id: "M41",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 4.5,
    size: "38 arcmin",
    ra: 6.7667,
    dec: -20.75,
    image: "images/full/m41.jpg",
    desc: "A bright open cluster near Sirius in Canis Major."
  },
  {
    id: "M42",
    name: "Orion Nebula",
    type: "Diffuse Nebula",
    mag: 4.0,
    size: "65x60 arcmin",
    ra: 5.5917,
    dec: -5.45,
    image: "images/full/m42.jpg",
    desc: "A massive star-forming region in Orion’s sword, visible to the naked eye."
  },
  {
    id: "M43",
    name: "De Mairan's Nebula",
    type: "Diffuse Nebula",
    mag: 9.0,
    size: "20 arcmin",
    ra: 5.6,
    dec: -5.2667,
    image: "images/full/m43.jpg",
    desc: "A bright knot of nebulosity next to the Orion Nebula."
  },
  {
    id: "M44",
    name: "Beehive Cluster",
    type: "Open Cluster",
    mag: 3.7,
    size: "95 arcmin",
    ra: 8.6667,
    dec: 19.6667,
    image: "images/full/m44.jpg",
    desc: "A bright open cluster in Cancer, visible to the naked eye."
  },
  {
    id: "M45",
    name: "Pleiades",
    type: "Open Cluster",
    mag: 1.6,
    size: "110 arcmin",
    ra: 3.7917,
    dec: 24.1167,
    image: "images/full/m45.jpg",
    desc: "The Seven Sisters, a famous open cluster in Taurus."
  },
  {
    id: "M46",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 6.1,
    size: "27 arcmin",
    ra: 7.7,
    dec: -14.8167,
    image: "images/full/m46.jpg",
    desc: "A rich cluster in Puppis with a planetary nebula superimposed."
  },
  {
    id: "M47",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 4.4,
    size: "30 arcmin",
    ra: 7.6333,
    dec: -14.5,
    image: "images/full/m47.jpg",
    desc: "A bright but sparse open cluster in Puppis."
  },
  {
    id: "M48",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.5,
    size: "54 arcmin",
    ra: 8.2167,
    dec: -5.75,
    image: "images/full/m48.jpg",
    desc: "A large open cluster in Hydra."
  },
  {
    id: "M49",
    name: "Elliptical Galaxy",
    type: "Galaxy",
    mag: 8.4,
    size: "9x7 arcmin",
    ra: 12.4978,
    dec: 8.0,
    image: "images/full/m49.jpg",
    desc: "A giant elliptical galaxy in Virgo, part of the Virgo Cluster."
  },
  {
    id: "M50",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 5.9,
    size: "16 arcmin",
    ra: 7.0333,
    dec: -8.3333,
    image: "images/full/m50.jpg",
    desc: "A pretty open cluster in Monoceros."
  },
  {
    id: "M51",
    name: "Whirlpool Galaxy",
    type: "Galaxy",
    mag: 8.4,
    size: "11x7 arcmin",
    ra: 13.4933,
    dec: 47.2,
    image: "images/full/m51.jpg",
    desc: "A classic spiral galaxy in Canes Venatici, interacting with NGC 5195."
  },
  {
    id: "M52",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 6.9,
    size: "13 arcmin",
    ra: 23.4667,
    dec: 61.6,
    image: "images/full/m52.jpg",
    desc: "A compact open cluster in Cassiopeia."
  },
  {
    id: "M53",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.7,
    size: "12 arcmin",
    ra: 13.2167,
    dec: 18.1667,
    image: "images/full/m53.jpg",
    desc: "A globular cluster in Coma Berenices."
  },
  {
    id: "M54",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.6,
    size: "9 arcmin",
    ra: 18.9167,
    dec: -30.4833,
    image: "images/full/m54.jpg",
    desc: "A globular cluster in Sagittarius, part of the Sagittarius Dwarf Galaxy."
  },
  {
    id: "M55",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.0,
    size: "19 arcmin",
    ra: 19.6667,
    dec: -30.9667,
    image: "images/full/m55.jpg",
    desc: "A loose globular cluster in Sagittarius."
  },
  {
    id: "M56",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 8.3,
    size: "7 arcmin",
    ra: 19.2667,
    dec: 30.1833,
    image: "images/full/m56.jpg",
    desc: "A small globular cluster in Lyra."
  },
  {
    id: "M57",
    name: "Ring Nebula",
    type: "Planetary Nebula",
    mag: 8.8,
    size: "1.4 arcmin",
    ra: 18.8833,
    dec: 33.0333,
    image: "images/full/m57.jpg",
    desc: "A famous planetary nebula in Lyra, shaped like a ring."
  },
  {
    id: "M58",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.7,
    size: "5.9x4.7 arcmin",
    ra: 12.6667,
    dec: 11.8167,
    image: "images/full/m58.jpg",
    desc: "A barred spiral galaxy in Virgo."
  },
  {
    id: "M59",
    name: "Elliptical Galaxy",
    type: "Galaxy",
    mag: 9.6,
    size: "5.4x4.6 arcmin",
    ra: 12.7,
    dec: 11.65,
    image: "images/full/m59.jpg",
    desc: "An elliptical galaxy in Virgo, near M60."
  },
  {
    id: "M60",
    name: "Elliptical Galaxy",
    type: "Galaxy",
    mag: 8.8,
    size: "7.6x6.2 arcmin",
    ra: 12.7333,
    dec: 11.55,
    image: "images/full/m60.jpg",
    desc: "A giant elliptical galaxy in Virgo, near M59."
  },
  {
    id: "M61",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.7,
    size: "6.5 arcmin",
    ra: 12.3667,
    dec: 4.4667,
    image: "images/full/m61.jpg",
    desc: "A face-on spiral galaxy in Virgo."
  },
  {
    id: "M62",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.5,
    size: "15 arcmin",
    ra: 17.0167,
    dec: -30.1167,
    image: "images/full/m62.jpg",
    desc: "A distorted globular cluster in Ophiuchus."
  },
  {
    id: "M63",
    name: "Sunflower Galaxy",
    type: "Galaxy",
    mag: 8.6,
    size: "12x7 arcmin",
    ra: 13.2667,
    dec: 42.0333,
    image: "images/full/m63.jpg",
    desc: "A spiral galaxy in Canes Venatici with bright spiral arms."
  },
  {
    id: "M64",
    name: "Black Eye Galaxy",
    type: "Galaxy",
    mag: 8.5,
    size: "9.3x5.4 arcmin",
    ra: 12.9167,
    dec: 21.6833,
    image: "images/full/m64.jpg",
    desc: "A spiral galaxy with a dark dust lane, in Coma Berenices."
  },
  {
    id: "M65",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.3,
    size: "10x3 arcmin",
    ra: 11.3,
    dec: 13.0833,
    image: "images/full/m65.jpg",
    desc: "A spiral galaxy in Leo, part of the Leo Triplet."
  },
  {
    id: "M66",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 8.9,
    size: "9x4 arcmin",
    ra: 11.3167,
    dec: 12.9833,
    image: "images/full/m66.jpg",
    desc: "A spiral galaxy in Leo, part of the Leo Triplet."
  },
  {
    id: "M67",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 6.9,
    size: "30 arcmin",
    ra: 8.8667,
    dec: 11.8167,
    image: "images/full/m67.jpg",
    desc: "An old open cluster in Cancer."
  },
  {
    id: "M68",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.3,
    size: "11 arcmin",
    ra: 12.6667,
    dec: -26.75,
    image: "images/full/m68.jpg",
    desc: "A globular cluster in Hydra."
  },
  {
    id: "M69",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.6,
    size: "7 arcmin",
    ra: 18.45,
    dec: -32.35,
    image: "images/full/m69.jpg",
    desc: "A compact globular cluster in Sagittarius."
  },
  {
    id: "M70",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.9,
    size: "7 arcmin",
    ra: 18.7167,
    dec: -32.3,
    image: "images/full/m70.jpg",
    desc: "A globular cluster in Sagittarius, near M69."
  },
  {
    id: "M71",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 8.4,
    size: "7 arcmin",
    ra: 19.8833,
    dec: 18.7833,
    image: "images/full/m71.jpg",
    desc: "A loose globular cluster in Sagitta."
  },
  {
    id: "M72",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 9.3,
    size: "6 arcmin",
    ra: 20.8917,
    dec: -12.5333,
    image: "images/full/m72.jpg",
    desc: "A faint globular cluster in Aquarius."
  },
  {
    id: "M73",
    name: "Asterism",
    type: "Asterism",
    mag: 9.0,
    size: "3 arcmin",
    ra: 20.9667,
    dec: -12.6333,
    image: "images/full/m73.jpg",
    desc: "A small asterism of four stars in Aquarius."
  },
  {
    id: "M74",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.4,
    size: "10.5 arcmin",
    ra: 1.6167,
    dec: 15.7833,
    image: "images/full/m74.jpg",
    desc: "A face-on spiral galaxy in Pisces."
  },
  {
    id: "M75",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 8.5,
    size: "6 arcmin",
    ra: 20.1167,
    dec: -21.9167,
    image: "images/full/m75.jpg",
    desc: "A compact globular cluster in Sagittarius."
  },
  {
    id: "M76",
    name: "Little Dumbbell Nebula",
    type: "Planetary Nebula",
    mag: 10.1,
    size: "2.7 arcmin",
    ra: 1.7,
    dec: 51.5667,
    image: "images/full/m76.jpg",
    desc: "A planetary nebula in Perseus."
  },
  {
    id: "M77",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 8.9,
    size: "7x6 arcmin",
    ra: 2.7167,
    dec: 0.0167,
    image: "images/full/m77.jpg",
    desc: "A bright spiral galaxy in Cetus, also a Seyfert galaxy."
  },
  {
    id: "M78",
    name: "Reflection Nebula",
    type: "Reflection Nebula",
    mag: 8.0,
    size: "8x6 arcmin",
    ra: 5.7667,
    dec: 0.05,
    image: "images/full/m78.jpg",
    desc: "A bright reflection nebula in Orion."
  },
  {
    id: "M79",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.7,
    size: "9 arcmin",
    ra: 5.4,
    dec: -24.55,
    image: "images/full/m79.jpg",
    desc: "A globular cluster in Lepus."
  },
  {
    id: "M80",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 7.3,
    size: "10 arcmin",
    ra: 16.2833,
    dec: -22.9833,
    image: "images/full/m80.jpg",
    desc: "A dense globular cluster in Scorpius."
  },
  {
    id: "M81",
    name: "Bode's Galaxy",
    type: "Spiral Galaxy",
    mag: 6.9,
    size: "27x14 arcmin",
    ra: 9.9167,
    dec: 69.0667,
    image: "images/full/m81.jpg",
    desc: "A bright spiral galaxy in Ursa Major, companion to M82."
  },
  {
    id: "M82",
    name: "Cigar Galaxy",
    type: "Irregular Galaxy",
    mag: 8.4,
    size: "11x5 arcmin",
    ra: 9.9333,
    dec: 69.6833,
    image: "images/full/m82.jpg",
    desc: "A starburst galaxy in Ursa Major, strongly interacting with M81."
  },
  {
    id: "M83",
    name: "Southern Pinwheel Galaxy",
    type: "Spiral Galaxy",
    mag: 7.6,
    size: "12x11 arcmin",
    ra: 13.6167,
    dec: -29.8667,
    image: "images/full/m83.jpg",
    desc: "A large barred spiral galaxy in Hydra."
  },
  {
    id: "M84",
    name: "Lenticular Galaxy",
    type: "Galaxy",
    mag: 9.1,
    size: "6x5 arcmin",
    ra: 12.25,
    dec: 12.8833,
    image: "images/full/m84.jpg",
    desc: "A galaxy in Virgo, part of Markarian’s Chain."
  },
  {
    id: "M85",
    name: "Lenticular Galaxy",
    type: "Galaxy",
    mag: 9.1,
    size: "7x5 arcmin",
    ra: 12.25,
    dec: 18.1917,
    image: "images/full/m85.jpg",
    desc: "A lenticular galaxy in Coma Berenices."
  },
  {
    id: "M86",
    name: "Lenticular Galaxy",
    type: "Galaxy",
    mag: 8.9,
    size: "9x6 arcmin",
    ra: 12.4333,
    dec: 12.95,
    image: "images/full/m86.jpg",
    desc: "A galaxy in Virgo, close to M84 in Markarian’s Chain."
  },
  {
    id: "M87",
    name: "Virgo A",
    type: "Elliptical Galaxy",
    mag: 8.6,
    size: "8x7 arcmin",
    ra: 12.5167,
    dec: 12.4,
    image: "images/full/m87.jpg",
    desc: "A giant elliptical galaxy in Virgo, famous for its black hole jet."
  },
  {
    id: "M88",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.6,
    size: "7x4 arcmin",
    ra: 12.45,
    dec: 14.4167,
    image: "images/full/m88.jpg",
    desc: "A bright spiral galaxy in Coma Berenices."
  },
  {
    id: "M89",
    name: "Elliptical Galaxy",
    type: "Galaxy",
    mag: 9.8,
    size: "5x5 arcmin",
    ra: 12.6167,
    dec: 12.5667,
    image: "images/full/m89.jpg",
    desc: "An elliptical galaxy in Virgo."
  },
  {
    id: "M90",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.5,
    size: "9.5x4.5 arcmin",
    ra: 12.6167,
    dec: 13.1667,
    image: "images/full/m90.jpg",
    desc: "A spiral galaxy in Virgo."
  },
  {
    id: "M91",
    name: "Barred Spiral Galaxy",
    type: "Galaxy",
    mag: 10.2,
    size: "5.4 arcmin",
    ra: 12.6333,
    dec: 14.5,
    image: "images/full/m91.jpg",
    desc: "A barred spiral galaxy in Coma Berenices."
  },
  {
    id: "M92",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 6.4,
    size: "14 arcmin",
    ra: 17.2833,
    dec: 43.1333,
    image: "images/full/m92.jpg",
    desc: "A bright globular cluster in Hercules."
  },
  {
    id: "M93",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 6.0,
    size: "22 arcmin",
    ra: 7.7167,
    dec: -23.8667,
    image: "images/full/m93.jpg",
    desc: "A rich open cluster in Puppis."
  },
  {
    id: "M94",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 8.2,
    size: "11x9 arcmin",
    ra: 12.8333,
    dec: 41.1167,
    image: "images/full/m94.jpg",
    desc: "A spiral galaxy in Canes Venatici with a bright ring."
  },
  {
    id: "M95",
    name: "Barred Spiral Galaxy",
    type: "Galaxy",
    mag: 9.7,
    size: "7.4 arcmin",
    ra: 10.7333,
    dec: 11.7,
    image: "images/full/m95.jpg",
    desc: "A barred spiral galaxy in Leo."
  },
  {
    id: "M96",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.2,
    size: "7.6 arcmin",
    ra: 10.8,
    dec: 11.8167,
    image: "images/full/m96.jpg",
    desc: "A spiral galaxy in Leo, part of the Leo I Group."
  },
  {
    id: "M97",
    name: "Owl Nebula",
    type: "Planetary Nebula",
    mag: 9.9,
    size: "3 arcmin",
    ra: 11.2333,
    dec: 55.0167,
    image: "images/full/m97.jpg",
    desc: "A planetary nebula in Ursa Major with two dark 'eyes'."
  },
  {
    id: "M98",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 10.1,
    size: "9.5x2.5 arcmin",
    ra: 12.2167,
    dec: 14.9,
    image: "images/full/m98.jpg",
    desc: "A spiral galaxy in Coma Berenices."
  },
  {
    id: "M99",
    name: "Pinwheel Galaxy",
    type: "Galaxy",
    mag: 9.9,
    size: "5.4 arcmin",
    ra: 12.3333,
    dec: 14.4167,
    image: "images/full/m99.jpg",
    desc: "A face-on spiral galaxy in Coma Berenices."
  },
  {
    id: "M100",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 9.4,
    size: "7x6 arcmin",
    ra: 12.3667,
    dec: 15.8167,
    image: "images/full/m100.jpg",
    desc: "A grand design spiral galaxy in Coma Berenices."
  },
  {
    id: "M101",
    name: "Pinwheel Galaxy",
    type: "Galaxy",
    mag: 7.9,
    size: "28 arcmin",
    ra: 14.05,
    dec: 54.35,
    image: "images/full/m101.jpg",
    desc: "A large face-on spiral galaxy in Ursa Major."
  },
  {
    id: "M102",
    name: "Spindle Galaxy",
    type: "Galaxy",
    mag: 9.9,
    size: "7x3 arcmin",
    ra: 15.0667,
    dec: 55.7667,
    image: "images/full/m102.jpg",
    desc: "A lenticular galaxy in Draco."
  },
  {
    id: "M103",
    name: "Open Cluster",
    type: "Open Cluster",
    mag: 7.4,
    size: "6 arcmin",
    ra: 1.55,
    dec: 60.7167,
    image: "images/full/m103.jpg",
    desc: "A small open cluster in Cassiopeia."
  },
  {
    id: "M104",
    name: "Sombrero Galaxy",
    type: "Galaxy",
    mag: 8.0,
    size: "8.7x3.5 arcmin",
    ra: 12.7167,
    dec: -11.6167,
    image: "images/full/m104.jpg",
    desc: "A striking edge-on galaxy with a dark dust lane in Virgo."
  },
  {
    id: "M105",
    name: "Elliptical Galaxy",
    type: "Galaxy",
    mag: 9.3,
    size: "4.6 arcmin",
    ra: 10.8,
    dec: 12.5833,
    image: "images/full/m105.jpg",
    desc: "An elliptical galaxy in Leo, near M95 and M96."
  },
  {
    id: "M106",
    name: "Spiral Galaxy",
    type: "Galaxy",
    mag: 8.4,
    size: "19x8 arcmin",
    ra: 12.3167,
    dec: 47.3,
    image: "images/full/m106.jpg",
    desc: "A bright spiral galaxy in Canes Venatici."
  },
  {
    id: "M107",
    name: "Globular Cluster",
    type: "Globular Cluster",
    mag: 8.1,
    size: "13 arcmin",
    ra: 16.55,
    dec: -13.05,
    image: "images/full/m107.jpg",
    desc: "A loose globular cluster in Ophiuchus."
  },
  {
    id: "M108",
    name: "Surfboard Galaxy",
    type: "Galaxy",
    mag: 10.0,
    size: "8x2 arcmin",
    ra: 11.2,
    dec: 55.6667,
    image: "images/full/m108.jpg",
    desc: "An edge-on spiral galaxy in Ursa Major."
  },
  {
    id: "M109",
    name: "Barred Spiral Galaxy",
    type: "Galaxy",
    mag: 9.8,
    size: "7.6x4.7 arcmin",
    ra: 11.9667,
    dec: 53.3833,
    image: "images/full/m109.jpg",
    desc: "A barred spiral galaxy in Ursa Major."
  },
  {
    id: "M110",
    name: "Satellite of Andromeda",
    type: "Dwarf Elliptical Galaxy",
    mag: 8.1,
    size: "21x11 arcmin",
    ra: 0.7167,
    dec: 41.6833,
    image: "images/full/m110.jpg",
    desc: "A dwarf elliptical companion galaxy to M31."
  }
];
